# Generated by Django 5.2 on 2026-03-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_ai_suggestions_userprofile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scheduled_deletion_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
