# Generated by Django 6.0.2 on 2026-03-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudequestions',
            name='subtopic',
            field=models.CharField(choices=[('Arithmetic', 'Arithmetic'), ('Time & Work', 'Time Work'), ('Profit & Loss', 'Profit Loss'), ('Percentages', 'Percentages'), ('Ratio & Proportion', 'Ratio Proportion'), ('Speed, Time & Distance', 'Speed Time Distance'), ('Permutation & Combination', 'Permutation Combination'), ('Probability', 'Probability'), ('Patterns', 'Patterns'), ('Syllogisms', 'Syllogisms'), ('Sequences', 'Sequences'), ('Synonyms', 'Synonyms'), ('Antonyms', 'Antonyms'), ('Comprehension', 'Comprehension'), ('Bar Graphs', 'Bar Graphs'), ('Pie Charts', 'Pie Charts'), ('Tables', 'Tables'), ('Data Structures', 'Data Structures'), ('Algorithms', 'Algorithms'), ('DBMS', 'Dbms'), ('None', 'None Sub')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='aptitudetest',
            name='subtopic',
            field=models.CharField(choices=[('Arithmetic', 'Arithmetic'), ('Time & Work', 'Time Work'), ('Profit & Loss', 'Profit Loss'), ('Percentages', 'Percentages'), ('Ratio & Proportion', 'Ratio Proportion'), ('Speed, Time & Distance', 'Speed Time Distance'), ('Permutation & Combination', 'Permutation Combination'), ('Probability', 'Probability'), ('Patterns', 'Patterns'), ('Syllogisms', 'Syllogisms'), ('Sequences', 'Sequences'), ('Synonyms', 'Synonyms'), ('Antonyms', 'Antonyms'), ('Comprehension', 'Comprehension'), ('Bar Graphs', 'Bar Graphs'), ('Pie Charts', 'Pie Charts'), ('Tables', 'Tables'), ('Data Structures', 'Data Structures'), ('Algorithms', 'Algorithms'), ('DBMS', 'Dbms'), ('None', 'None Sub')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='aptitudequestions',
            name='category',
            field=models.CharField(choices=[('Quantitative Aptitude', 'Quantitative Aptitude'), ('Logical Reasoning', 'Logical Reasoning'), ('Verbal Ability', 'Verbal Ability'), ('Data Interpretation', 'Data Interpretation'), ('Technical Aptitude', 'Technical Aptitude'), ('All Categories', 'All Categories')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aptitudetest',
            name='category',
            field=models.CharField(choices=[('Quantitative Aptitude', 'Quantitative Aptitude'), ('Logical Reasoning', 'Logical Reasoning'), ('Verbal Ability', 'Verbal Ability'), ('Data Interpretation', 'Data Interpretation'), ('Technical Aptitude', 'Technical Aptitude'), ('All Categories', 'All Categories')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aptitudetest',
            name='test_mode',
            field=models.CharField(choices=[('Practice Mode', 'Practice Mode'), ('Exam Mode', 'Exam Mode'), ('Full Developer Mock', 'Full Mock Test')], max_length=50),
        ),
    ]
