# Generated by Django 6.0.2 on 2026-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0002_aptitudequestions_subtopic_aptitudetest_subtopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudequestions',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aptitudequestions',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aptitudequestions',
            name='question_text',
            field=models.TextField(),
        ),
    ]
